-- HCSP-OM PRD work report schema.
-- Run in Supabase SQL Editor before using report attachments.

create table if not exists public.work_reports (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  report_title text not null,
  report_date date not null default current_date,
  notes text,
  created_by uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.work_report_attachments (
  id bigint generated by default as identity primary key,
  work_report_id bigint not null references public.work_reports(id) on delete cascade,
  order_id bigint not null references public.orders(id) on delete cascade,
  file_name text not null,
  file_path text not null,
  file_size bigint,
  file_type text,
  uploaded_by uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists idx_work_reports_order_id on public.work_reports(order_id);
create index if not exists idx_work_reports_created_by on public.work_reports(created_by);
create index if not exists idx_work_report_attachments_report_id on public.work_report_attachments(work_report_id);
create index if not exists idx_work_report_attachments_order_id on public.work_report_attachments(order_id);

-- Optional one-time migration from the scaffold table used by older app iterations.
do $$
begin
  if to_regclass('public.reports') is not null then
    insert into public.work_reports (id, order_id, report_title, notes, created_at)
    overriding system value
    select id, order_id, report_title, report_description, created_at
    from public.reports
    on conflict (id) do nothing;

    perform setval(
      pg_get_serial_sequence('public.work_reports', 'id'),
      greatest((select coalesce(max(id), 1) from public.work_reports), 1)
    );
  end if;
end $$;

insert into storage.buckets (id, name, public)
values ('work-report-attachments', 'work-report-attachments', false)
on conflict (id) do nothing;

alter table public.work_reports enable row level security;
alter table public.work_report_attachments enable row level security;

drop policy if exists "Work reports are visible by role" on public.work_reports;
drop policy if exists "Work reports are visible to authenticated users" on public.work_reports;
create policy "Work reports are visible by role"
on public.work_reports for select
to authenticated
using (
  exists (
    select 1 from public.users u
    where u.id = auth.uid()
      and (
        lower(u.role) like '%admin%'
        or lower(u.role) like '%hcam%'
        or lower(u.role) like '%manage%'
      )
  )
  or exists (
    select 1 from public.orders o
    where o.id = work_reports.order_id
      and o.created_by = auth.uid()
  )
  or exists (
    select 1 from public.order_assignments oa
    where oa.order_id = work_reports.order_id
      and oa.user_id = auth.uid()
  )
);

drop policy if exists "Team can insert work reports" on public.work_reports;
create policy "Team can insert work reports"
on public.work_reports for insert
to authenticated
with check (
  exists (
    select 1 from public.users u
    where u.id = auth.uid()
      and lower(u.role) like '%team%'
  )
  and created_by = auth.uid()
  and exists (
    select 1 from public.orders o
    join public.order_assignments oa on oa.order_id = o.id
    where o.id = work_reports.order_id
      and oa.user_id = auth.uid()
      and o.status in ('In Progress', 'Review')
  )
);

drop policy if exists "Admins can delete work reports" on public.work_reports;
create policy "Admins can delete work reports"
on public.work_reports for delete
to authenticated
using (
  exists (
    select 1 from public.users u
    where u.id = auth.uid()
      and lower(u.role) like '%admin%'
  )
);

drop policy if exists "Work report attachments are visible by role" on public.work_report_attachments;
drop policy if exists "Work report attachments are visible to authenticated users" on public.work_report_attachments;
create policy "Work report attachments are visible by role"
on public.work_report_attachments for select
to authenticated
using (
  exists (
    select 1 from public.work_reports wr
    where wr.id = work_report_attachments.work_report_id
      and (
        exists (
          select 1 from public.users u
          where u.id = auth.uid()
            and (
              lower(u.role) like '%admin%'
              or lower(u.role) like '%hcam%'
              or lower(u.role) like '%manage%'
            )
        )
        or exists (
          select 1 from public.orders o
          where o.id = wr.order_id
            and o.created_by = auth.uid()
        )
        or exists (
          select 1 from public.order_assignments oa
          where oa.order_id = wr.order_id
            and oa.user_id = auth.uid()
        )
      )
  )
);

drop policy if exists "Team can insert work report attachments" on public.work_report_attachments;
create policy "Team can insert work report attachments"
on public.work_report_attachments for insert
to authenticated
with check (
  exists (
    select 1 from public.users u
    where u.id = auth.uid()
      and lower(u.role) like '%team%'
  )
  and uploaded_by = auth.uid()
  and exists (
    select 1 from public.work_reports wr
    join public.orders o on o.id = wr.order_id
    join public.order_assignments oa on oa.order_id = wr.order_id
    where wr.id = work_report_attachments.work_report_id
      and wr.order_id = work_report_attachments.order_id
      and oa.user_id = auth.uid()
      and o.status in ('In Progress', 'Review')
  )
);

drop policy if exists "Admins can delete work report attachments" on public.work_report_attachments;
create policy "Admins can delete work report attachments"
on public.work_report_attachments for delete
to authenticated
using (
  exists (
    select 1 from public.users u
    where u.id = auth.uid()
      and lower(u.role) like '%admin%'
  )
);

drop policy if exists "Authenticated users can upload work report files" on storage.objects;
create policy "Authenticated users can upload work report files"
on storage.objects for insert
to authenticated
with check (bucket_id = 'work-report-attachments');

drop policy if exists "Authenticated users can read work report files" on storage.objects;
create policy "Authenticated users can read work report files"
on storage.objects for select
to authenticated
using (bucket_id = 'work-report-attachments');

drop policy if exists "Admins can delete work report files" on storage.objects;
create policy "Admins can delete work report files"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'work-report-attachments'
  and exists (
    select 1 from public.users u
    where u.id = auth.uid()
      and lower(u.role) like '%admin%'
  )
);
